const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.Anchor,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.video.Acts.SetOpacity,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Vídeo: 0},
	{fondomenu: 0},
	{botonjugar: 0},
	{botoncreditos: 0},
	{Titulo: 0},
	{Mouse: 0},
	{Teclado: 0},
	{Creditos: 0},
	{botoncerrar: 0},
	{Mapa: 0},
	{personaje: 0},
	{jefe: 0},
	{cargando: 0},
	{fondoboos: 0},
	{Sólido: 0},
	{jugador: 0},
	{Limite1: 0},
	{Limite2: 0},
	{Limite3: 0},
	{Ancla: 0},
	{Limite4: 0},
	{botones: 0},
	{Sprite: 0},
	{MoverA: 0},
	{bala: 0},
	{bala2: 0},
	{Ataque: 0},
	{Texto: 0},
	{Texto2: 0},
	{ganapierde: 0},
	{ganapierde2: 0},
	{vidaJefe: 0},
	{daño: 0},
	{descanso: 0},
	{fusilamiento: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Vídeo: class extends self.IWorldInstance {},
	fondomenu: class extends self.ITiledBackgroundInstance {},
	botonjugar: class extends self.ISpriteInstance {},
	botoncreditos: class extends self.ISpriteInstance {},
	Titulo: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	Creditos: class extends self.ISpriteInstance {},
	botoncerrar: class extends self.ISpriteInstance {},
	Mapa: class extends self.ITiledBackgroundInstance {},
	personaje: class extends self.ISpriteInstance {},
	jefe: class extends self.ISpriteInstance {},
	cargando: class extends self.ISpriteInstance {},
	fondoboos: class extends self.ITiledBackgroundInstance {},
	jugador: class extends self.ISpriteInstance {},
	Limite1: class extends self.ISpriteInstance {},
	Limite2: class extends self.ISpriteInstance {},
	Limite3: class extends self.ISpriteInstance {},
	Limite4: class extends self.ISpriteInstance {},
	botones: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	bala: class extends self.ISpriteInstance {},
	bala2: class extends self.ISpriteInstance {},
	Ataque: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	ganapierde: class extends self.ITextInstance {},
	ganapierde2: class extends self.ITextInstance {}
}